plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()
}

// Firstly requires:
//    ./gradlew :java:shading:module2:publishToMavenLocal

dependencies {
    implementation          'education:module2-shaded:0.1'
}

compileJava.dependsOn       ':java:shading:module2:publishToMavenLocal'

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['resources']
        }
    }
}

