plugins {
    id 'java'
}

group = 'education'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

allprojects {
    tasks.withType(Test) {
        useJUnitPlatform()
        outputs.upToDateWhen { false }
        testLogging {
            events = ["passed", "skipped", "failed"]
            exceptionFormat = "full"
            showExceptions = true
            showCauses = true
            showStackTraces = true
            showStandardStreams = true
            displayGranularity = 2
        }
    }
}

test {
    dependsOn(':java:common:test')
    dependsOn(':java:syntax:test')
    dependsOn(':java:jackson:test')
    dependsOn(':java:maths:test')
    dependsOn(':java:vertx:test')
}