rootProject.name = 'education'

include 'java:ai'
include 'java:benchmarks'
include 'java:common'
include 'java:cryptography'
include 'java:designpatterns'
include 'java:jackson'
include 'java:maths'
include 'java:networking'
include 'java:selenium'
include 'java:simpledsl'
include 'java:syntax'
include 'java:vertx'
include 'java:yaml'

include 'java:openapi:code-first'
include 'java:openapi:spec-first'

include 'java:websockets:communications'
include 'java:websockets:infrastructure'
include 'java:websockets:websockets-vertx'
include 'java:websockets:client'
include 'java:websockets:server'
include 'java:websockets:testing:integration'
include 'java:1brc'
include 'java:quantum'

include 'java:shading:module1'
include 'java:shading:module2'
