rootProject.name = 'education'

include 'java:selenium'
include 'java:common'
include 'java:syntax'
include 'java:jackson'
include 'java:maths'
include 'java:vertx'
include 'java:yaml'

include 'java:websockets:communications'
include 'java:websockets:infrastructure'
include 'java:websockets:websockets-vertx'
include 'java:websockets:client'
include 'java:websockets:server'
include 'java:websockets:testing:integration'

include 'ai'
include 'ai:local-llm'
include 'ai:text-to-image'
include 'ai:text-to-image:automatic1111'

include 'advent-of-code:2025'

