plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation          "io.vertx:vertx-core:5.0.12"
    testImplementation          "io.vertx:vertx-web:5.0.12"

    testImplementation          project(':java:openapi:common')
    testImplementation          project(':java:openapi:code-first')
    testImplementation          project(':java:common')

    testImplementation      platform('org.junit:junit-bom:5.10.0')
    testImplementation      'org.junit.jupiter:junit-jupiter-engine:5.13.4'
    testRuntimeOnly         'org.junit.platform:junit-platform-launcher'
    testImplementation      "io.vertx:vertx-web-client:5.0.12"
    testImplementation      'org.assertj:assertj-core:3.27.7'
}

test {
    useJUnitPlatform()
}