plugins {
    id 'java'
    id 'maven-publish'
    id 'io.github.goooler.shadow' version '8.1.8'
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['resources']
        }
    }
}

shadowJar {
    archiveClassifier.set('')
    relocate 'education', 'education.shaded'
}

publishing {
    publications {
        shadow(MavenPublication) {
            groupId = 'education'
            artifactId = 'module2-shaded'
            version = '0.1'
            artifact shadowJar
        }
    }
    repositories {
        mavenLocal()
    }
}

assemble.dependsOn             shadowJar