plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation      platform('org.junit:junit-bom:5.10.0')
    testImplementation      'org.junit.jupiter:junit-jupiter-engine:5.13.4'
    testRuntimeOnly         'org.junit.platform:junit-platform-launcher'

    implementation          'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation          'io.vertx:vertx-core:5.0.11'
    implementation          'io.vertx:vertx-web:5.0.11'
//    implementation          'org.slf4j:slf4j-simple:2.0.17'

    testImplementation      'io.vertx:vertx-core:5.0.11'
    testImplementation      'org.assertj:assertj-core:3.27.4'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['resources']
        }
    }
    test {
        java {
            srcDirs = ['test']
        }
        resources {
            srcDirs = ['resources']
        }
    }
}

test {
    useJUnitPlatform()
}