plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation      platform('org.junit:junit-bom:5.10.0')
    testImplementation      'org.junit.jupiter:junit-jupiter-engine:5.13.4'
    testRuntimeOnly         'org.junit.platform:junit-platform-launcher'

    implementation          'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation          'org.slf4j:slf4j-simple:2.0.17'
    implementation          'io.vertx:vertx-core:5.0.4'
    implementation          project(':java:common')
    implementation          project(':java:websockets:infrastructure')
    implementation          project(':java:websockets:server')
    implementation          project(':java:websockets:websockets-vertx')
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['resources']
        }
    }
}